/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cube/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserCubes"][];
                        "application/json": components["schemas"]["UserCubes"][];
                        "text/json": components["schemas"]["UserCubes"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Card: {
            /** Format: int32 */
            cardId?: number;
            name: string | null;
            /** Format: int32 */
            oracleId?: number;
        };
        CardInCube: {
            /** Format: int32 */
            cardInCubeId?: number;
            cube?: components["schemas"]["Cube"];
            card?: components["schemas"]["Card"];
        };
        Cube: {
            /** Format: int32 */
            cubeId: number;
            cubeName: string | null;
            user: components["schemas"]["User"];
            cardsInCube?: components["schemas"]["CardInCube"][] | null;
        };
        User: {
            /** Format: int32 */
            userId: number;
            name: string | null;
            cubes?: components["schemas"]["Cube"][] | null;
        };
        UserCubes: {
            cubeName?: string | null;
            cube?: components["schemas"]["Cube"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
