// This file is auto-generated by @hey-api/openapi-ts

export const $UserCubeModel = {
    type: 'object',
    properties: {
        cubeName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;