// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetApiV1CubeByUserIdData, GetApiV1CubeByUserIdResponse } from './types.gen';

export class CubeService {
    /**
     * @param data The data for the request.
     * @param data.userId
     * @returns UserCubeModel OK
     * @throws ApiError
     */
    public static getApiV1CubeByUserId(data: GetApiV1CubeByUserIdData): CancelablePromise<GetApiV1CubeByUserIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/cube/{userId}',
            path: {
                userId: data.userId
            }
        });
    }
    
}