// This file is auto-generated by @hey-api/openapi-ts

export type UserCubeModel = {
    cubeName?: string | null;
};

export type GetApiV1CubeByUserIdData = {
    userId: number;
};

export type GetApiV1CubeByUserIdResponse = Array<UserCubeModel>;

export type $OpenApiTs = {
    '/api/v1/cube/{userId}': {
        get: {
            req: GetApiV1CubeByUserIdData;
            res: {
                /**
                 * OK
                 */
                200: Array<UserCubeModel>;
            };
        };
    };
};