// This file is auto-generated by @hey-api/openapi-ts

export type LoginRequest = {
    email?: string | null;
    password?: string | null;
    nonce?: string;
};

export type LoginResponse = {
    success?: boolean;
};

export type UserCubeModel = {
    cubeName?: string | null;
};

export type GetApiV1AuthNonceResponse = string;

export type PostApiV1AuthLoginData = {
    requestBody?: LoginRequest;
};

export type PostApiV1AuthLoginResponse = LoginResponse;

export type GetApiV1CubeByUserIdData = {
    userId: string;
};

export type GetApiV1CubeByUserIdResponse = Array<UserCubeModel>;

export type $OpenApiTs = {
    '/api/v1/auth/nonce': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: string;
            };
        };
    };
    '/api/v1/auth/login': {
        post: {
            req: PostApiV1AuthLoginData;
            res: {
                /**
                 * OK
                 */
                200: LoginResponse;
            };
        };
    };
    '/api/v1/cube/{userId}': {
        get: {
            req: GetApiV1CubeByUserIdData;
            res: {
                /**
                 * OK
                 */
                200: Array<UserCubeModel>;
            };
        };
    };
};